version: '3.8'

services:
  web:
    build: .
    ports:
      - "9036:9036"
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./models:/app/models
    restart: unless-stopped
